//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIDEMO.ServiceOVTG {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOVTG.IServiceOVTG")]
    public interface IServiceOVTG {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOVTG/ShowOVTG", ReplyAction="http://tempuri.org/IServiceOVTG/ShowOVTGResponse")]
        System.Data.DataTable ShowOVTG();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOVTG/ShowOVTG", ReplyAction="http://tempuri.org/IServiceOVTG/ShowOVTGResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowOVTGAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOVTGChannel : GUIDEMO.ServiceOVTG.IServiceOVTG, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOVTGClient : System.ServiceModel.ClientBase<GUIDEMO.ServiceOVTG.IServiceOVTG>, GUIDEMO.ServiceOVTG.IServiceOVTG {
        
        public ServiceOVTGClient() {
        }
        
        public ServiceOVTGClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOVTGClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOVTGClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOVTGClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ShowOVTG() {
            return base.Channel.ShowOVTG();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowOVTGAsync() {
            return base.Channel.ShowOVTGAsync();
        }
    }
}
