//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIDEMO.ServiceOCPR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOCPR.IServiceOCPR")]
    public interface IServiceOCPR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOCPR/ShowContactPerson", ReplyAction="http://tempuri.org/IServiceOCPR/ShowContactPersonResponse")]
        System.Data.DataTable ShowContactPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOCPR/ShowContactPerson", ReplyAction="http://tempuri.org/IServiceOCPR/ShowContactPersonResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowContactPersonAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOCPRChannel : GUIDEMO.ServiceOCPR.IServiceOCPR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOCPRClient : System.ServiceModel.ClientBase<GUIDEMO.ServiceOCPR.IServiceOCPR>, GUIDEMO.ServiceOCPR.IServiceOCPR {
        
        public ServiceOCPRClient() {
        }
        
        public ServiceOCPRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOCPRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOCPRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOCPRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ShowContactPerson() {
            return base.Channel.ShowContactPerson();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowContactPersonAsync() {
            return base.Channel.ShowContactPersonAsync();
        }
    }
}
