//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIDEMO.ServiceOITM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOITM.IServiceOITM")]
    public interface IServiceOITM {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOITM/showOITM", ReplyAction="http://tempuri.org/IServiceOITM/showOITMResponse")]
        System.Data.DataTable showOITM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOITM/showOITM", ReplyAction="http://tempuri.org/IServiceOITM/showOITMResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showOITMAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOITMChannel : GUIDEMO.ServiceOITM.IServiceOITM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOITMClient : System.ServiceModel.ClientBase<GUIDEMO.ServiceOITM.IServiceOITM>, GUIDEMO.ServiceOITM.IServiceOITM {
        
        public ServiceOITMClient() {
        }
        
        public ServiceOITMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOITMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOITMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOITMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable showOITM() {
            return base.Channel.showOITM();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showOITMAsync() {
            return base.Channel.showOITMAsync();
        }
    }
}
