//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIDEMO.ServiceOCRD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOCRD.IServiceOCRD")]
    public interface IServiceOCRD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOCRD/showOCRD", ReplyAction="http://tempuri.org/IServiceOCRD/showOCRDResponse")]
        System.Data.DataTable showOCRD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOCRD/showOCRD", ReplyAction="http://tempuri.org/IServiceOCRD/showOCRDResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showOCRDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOCRD/searchOCRD", ReplyAction="http://tempuri.org/IServiceOCRD/searchOCRDResponse")]
        System.Data.DataTable searchOCRD(string keySearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOCRD/searchOCRD", ReplyAction="http://tempuri.org/IServiceOCRD/searchOCRDResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> searchOCRDAsync(string keySearch);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOCRDChannel : GUIDEMO.ServiceOCRD.IServiceOCRD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOCRDClient : System.ServiceModel.ClientBase<GUIDEMO.ServiceOCRD.IServiceOCRD>, GUIDEMO.ServiceOCRD.IServiceOCRD {
        
        public ServiceOCRDClient() {
        }
        
        public ServiceOCRDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOCRDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOCRDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOCRDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable showOCRD() {
            return base.Channel.showOCRD();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showOCRDAsync() {
            return base.Channel.showOCRDAsync();
        }
        
        public System.Data.DataTable searchOCRD(string keySearch) {
            return base.Channel.searchOCRD(keySearch);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> searchOCRDAsync(string keySearch) {
            return base.Channel.searchOCRDAsync(keySearch);
        }
    }
}
