//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIDEMO.ServiceOWHS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOWHS.IServiceOWHS")]
    public interface IServiceOWHS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOWHS/ShowOWHS", ReplyAction="http://tempuri.org/IServiceOWHS/ShowOWHSResponse")]
        System.Data.DataTable ShowOWHS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOWHS/ShowOWHS", ReplyAction="http://tempuri.org/IServiceOWHS/ShowOWHSResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowOWHSAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOWHSChannel : GUIDEMO.ServiceOWHS.IServiceOWHS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOWHSClient : System.ServiceModel.ClientBase<GUIDEMO.ServiceOWHS.IServiceOWHS>, GUIDEMO.ServiceOWHS.IServiceOWHS {
        
        public ServiceOWHSClient() {
        }
        
        public ServiceOWHSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOWHSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOWHSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOWHSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ShowOWHS() {
            return base.Channel.ShowOWHS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowOWHSAsync() {
            return base.Channel.ShowOWHSAsync();
        }
    }
}
